---
abstract: 'Statik is a lightweight text-based static blogging engine, inspired by blosxom'
author:
  - 'Gavin Carr <gavin@openfusion.com.au>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statik
no_index:
  directory:
    - inc
    - t
    - themes
requires:
  perl: 5.6.0
  Config::Tiny: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  DateTime::Format::RFC3339: 0
  Encode: 0
  Exporter::Lite: 0
  Hash::Merge: 0
  JSON: 0
  parent: 0
  Text::MicroMason: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
